// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwilw-LfPVGX_psP2kWfps7IST7_zkkE',
    appId: '1:25026313145:web:4fb300cdb348be9a105468',
    messagingSenderId: '25026313145',
    projectId: 'projetoplotze-392ef',
    authDomain: 'projetoplotze-392ef.firebaseapp.com',
    storageBucket: 'projetoplotze-392ef.firebasestorage.app',
    measurementId: 'G-7WN103N5G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpDKl_PPrUEkmLZn0WHSTAi3bJZ2Hdyzo',
    appId: '1:25026313145:android:c743c5d07642bcee105468',
    messagingSenderId: '25026313145',
    projectId: 'projetoplotze-392ef',
    storageBucket: 'projetoplotze-392ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lfft7VH4JwEzu5ro_5HMFFLiuuMn1kI',
    appId: '1:25026313145:ios:e68e17836e4f2b50105468',
    messagingSenderId: '25026313145',
    projectId: 'projetoplotze-392ef',
    storageBucket: 'projetoplotze-392ef.firebasestorage.app',
    iosBundleId: 'com.example.projetoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lfft7VH4JwEzu5ro_5HMFFLiuuMn1kI',
    appId: '1:25026313145:ios:e68e17836e4f2b50105468',
    messagingSenderId: '25026313145',
    projectId: 'projetoplotze-392ef',
    storageBucket: 'projetoplotze-392ef.firebasestorage.app',
    iosBundleId: 'com.example.projetoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEwilw-LfPVGX_psP2kWfps7IST7_zkkE',
    appId: '1:25026313145:web:e87d9d7c3b317ad4105468',
    messagingSenderId: '25026313145',
    projectId: 'projetoplotze-392ef',
    authDomain: 'projetoplotze-392ef.firebaseapp.com',
    storageBucket: 'projetoplotze-392ef.firebasestorage.app',
    measurementId: 'G-MHSEYXW8BE',
  );
}
